apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: elasticsearch-example
build:
  artifacts:
  - image: shopping-elastic-app-deployment
    context: ./
    sync:
      manual:
      - src: './*'
        dest: /app/*
deploy:
  kubectl:
    manifests:
      - ./k8s/*
      # k8s_elastic contains the configuration files for deploying elastic search. comment next line if elastic search is already deployed
      # - ./k8s_elastic/*