apiVersion: v1
kind: Service
metadata:
  name: shopping-elastic-app-service
spec:
  type: NodePort
  selector:
    component: shopping-elastic-app
  ports:
  - port: 3050
    targetPort: 3000
    nodePort: 30200
