apiVersion: v1
kind: Service
metadata:
  name: songs-elastic-app-service
spec:
  type: NodePort
  selector:
    component: songs-elastic-app
  ports:
  - port: 3050
    targetPort: 3000
    nodePort: 30200
