apiVersion: v1
kind: Service
metadata:
  name: elastic-search-service
  # namespace: operators
spec:
  selector:
    component: elastic
  ports:
  - name: http
    port: 9200
    targetPort: 9200
  - name: internal
    port: 9300
    targetPort: 9300
